from re import M
from pandas.core.frame import DataFrame

# Missing value dictionary for preprocessing
MISSING_VALUE_TABLE = {
    "light_conditions": [-1],
    "special_conditions_at_site": [-1, 9],
    "road_surface_conditions": [-1, 9, 6, 7],
    "junction_control": [-1, 0, 9],
    "junction_detail": [99, -1],
    "time": [],
    "speed_limit": [-1, 660, 630],
    "local_authority_district": [-1],
}

LIGHT_CONDITIONS = {
    'Daylight',
    'Darkness: street lights present and lit',
    'Darkness: street lights present but unlit',
    'Darkness: no street lighting',
    'Darkness: street lighting unknown',
}

SPECIAL_CONDITIONS_AT_SITE = {
    'None',
    'Auto traffic signal out',
    'Auto traffic signal partially defective',
    'Permanent road signing or marking defective or obscured',
    'Roadworks',
    'Road surface defective',
    'Oil or diesel',
    'Mud',
}

ROAD_SURFACE_CONDITIONS = {
    'Dry',
    'Wet / Damp',
    'Snow',
    'Frost / Ice',
    'Flood (surface water over 3cm deep)',
}

JUNCTION_CONTROL = {
    'Authorised person',
    'Automatic traffic signal',
    'Stop sign', 
    'Give way or uncontrolled',
}

JUNCTION_DETAIL = {
    'Not at or within 20 metres of junction',
    'Roundabout',
    'Mini roundabout',
    'T or staggered junction',
    'Slip road',
    'Crossroads',
    'Junction more than four arms (not RAB)',
    'Using private drive or entrance',
    'Other junction',
}

DISCRETE_COL = {
    'Plotly',
    'D3',
    'G10',
    'T10',
    'Alphabet',
    'Dark24',
    'Light24',
    'Set1',
    'Pastel1',
    'Dark2',
    'Set2',
    'Pastel2',
    'Set3',
    'Antique',
    'Bold',
    'Pastel',
    'Prism',
    'Safe',
    'Vivid',
}

SEQ_CONT_COL = {
    'Plotly3',
    'Viridis',
    'Cividis',
    'Inferno',
    'Magma',
    'Plasma',
    'Turbo',
    'Blackbody',
    'Bluered',
    'Electric',
    'Hot',
    'Jet',
    'Rainbow',
    'Blues',
    'BuGn',
    'BuPu',
    'GnBu',
    'Greens',
    'Greys',
    'OrRd',
    'Oranges',
    'PuBu',
    'PuBuGn',
    'PuRd',
    'Purples',
    'RdPu',
    'Reds',
    'YlGn',
    'YlGnBu',
    'YlOrBr',
    'YlOrRd',
    'turbid',
    'thermal',
    'haline',
    'solar',
    'ice',
    'gray',
    'deep',
    'dense',
    'algae',
    'matter',
    'speed',
    'amp',
    'tempo',
    'Burg',
    'Burgyl',
    'Redor',
    'Oryel',
    'Peach',
    'Pinkyl',
    'Mint',
    'Blugrn',
    'Darkmint',
    'Emrld',
    'Aggrnyl',
    'Bluyl',
    'Teal',
    'Tealgrn',
    'Purp',
    'Purpor',
    'Sunset',
    'Magenta',
    'Sunsetdark',
    'Agsunset',
    'Brwnyl'
}

CATEGORICAL_ATTRIBS = [
    'speed_limit',
    'light_conditions',
    'junction_detail',
    'junction_control',
    'road_surface_conditions',
    'special_conditions_at_site',
]

QUANTITATIVE_ATTRIBS = [
    'time',
    'accident_count',
    'fatality_rate',
]

SORT_ORDER_OPTIONS = [
    'None',
    'Ascending',
    'Descending',
]
ID_TO_LIGHT_CONDITIONS = {
    1 : 'Daylight',
    4 : 'Darkness: street lights present and lit',
    5 : 'Darkness: street lights present but unlit',
    6 : 'Darkness: no street lighting',
    7 : 'Darkness: street lighting unknown',
}

ID_TO_JUNCTION_DETAIL = {
    0 : 'Not at or within 20 metres of junction',
    1 : 'Roundabout',
    2 : 'Mini roundabout',
    3 : 'T or staggered junction',
    5 : 'Slip road',
    6 : 'Crossroads',
    7 : 'Junction more than four arms (not RAB)',
    8 : 'Using private drive or entrance',
    9 : 'Other junction',
}

ID_TO_JUNCTION_CONTROL = {
    1 : 'Authorised person',
    2 : 'Automatic traffic signal',
    3 : 'Stop sign', 
    4 : 'Give way or uncontrolled',
}

ID_TO_ROAD_SURFACE_CONDITIONS = {
    1 : 'Dry',
    2 : 'Wet / Damp',
    3 : 'Snow',
    4 : 'Frost / Ice',
    5 : 'Flood (surface water over 3cm deep)',
}

ID_TO_SPECIAL_CONDITIONS_AT_SITE = {
    0 : 'None',
    1 : 'Auto traffic signal out',
    2 : 'Auto traffic signal partially defective',
    3 : 'Permanent road signing or marking defective or obscured',
    4 : 'Roadworks',
    5 : 'Road surface defective',
    6 : 'Oil or diesel',
    7 : 'Mud',
}

ID_TO_POLICE_FORCE_AREA = {
    1 : 'Metropolitan Police',
    3 : 'Cumbria',
    4 : 'Lancashire',
    5 : 'Merseyside',
    6 : 'Greater Manchester',
    7 : 'Cheshire',
    10: 'Northumbria',
    11: 'Durham',
    12: 'North Yorkshire',
    13: 'West Yorkshire',
    14: 'South Yorkshire',
    16: 'Humberside',
    17: 'Cleveland',
    20: 'West Midlands',
    21: 'Staffordshire',
    22: 'West Mercia',
    23: 'Warwickshire',
    30: 'Derbyshire',
    31: 'Nottinghamshire',
    32: 'Lincolnshire',
    33: 'Leicestershire',
    34: 'Northamptonshire',
    35: 'Cambridgeshire',
    36: 'Norfolk',
    37: 'Suffolk',
    40: 'Bedfordshire',
    41: 'Hertfordshire',
    42: 'Essex',
    43: 'Thames Valley',
    44: 'Hampshire',
    45: 'Surrey',
    46: 'Kent',
    47: 'Sussex',
    48: 'City of London',
    50: 'Devon & Cornwall',
    52: 'Avon and Somerset',
    53: 'Gloucestershire',
    54: 'Wiltshire',
    55: 'Dorset',
    60: 'North Wales',
    61: 'Gwent',
    62: 'South Wales',
    63: 'Dyfed-Powys',
}

# Based on this dataset:
# https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/policeforceareadatatables
POPULATION_BY_POLICE_FORCE_AREA = {
    'Metropolitan Police': 8991600,
    'Cumbria':              499800,
    'Lancashire':          1515500,
    'Merseyside':          1434300,
    'Greater Manchester':  2848300,
    'Cheshire':            1069600,
    'Northumbria':         1470400,
    'Durham':               640600,
    'North Yorkshire':      831600,
    'West Yorkshire':      2345200,
    'South Yorkshire':     1415100,
    'Humberside':           934400,
    'Cleveland':            569800,
    'West Midlands':       2939900,
    'Staffordshire':       1139800,
    'West Mercia':         1298400,
    'Warwickshire':         583800,
    'Derbyshire':          1064000,
    'Nottinghamshire':     1170500,
    'Lincolnshire':         766300,
    'Leicestershire':      1107600,
    'Northamptonshire':     757200,
    'Cambridgeshire':       859800,
    'Norfolk':              914000,
    'Suffolk':              761200,
    'Bedfordshire':         682300,
    'Hertfordshire':       1195700,
    'Essex':               1856100,
    'Thames Valley':       2431900,
    'Hampshire':           1999100,
    'Surrey':              1199900,
    'Kent':                1868200,
    'Sussex':              1718200,
    'City of London':        10900,
    'Devon & Cornwall':    1785300,
    'Avon and Somerset':   1729500,
    'Gloucestershire':      640700,
    'Wiltshire':            727000,
    'Dorset':               776800,
    'North Wales':          703400,
    'Gwent':                598200,
    'South Wales':         1345300,
    'Dyfed-Powys':          522700,
}

ID_TO_LOCAL_DISTRICT = {
    1 :"Westminster",
    2 :"Camden",
    3 :"Islington",
    4 :"Hackney",
    5 :"Tower Hamlets",
    6 :"Greenwich",
    7 :"Lewisham",
    8 :"Southwark",
    9 :"Lambeth",
    10:"Wandsworth",
    11:"Hammersmith and Fulham",
    12:"Kensington and Chelsea",
    13:"Waltham Forest",
    14:"Redbridge",
    15:"Havering",
    16:"Barking and Dagenham",
    17:"Newham",
    18:"Bexley",
    19:"Bromley",
    20:"Croydon",
    21:"Sutton",
    22:"Merton",
    23:"Kingston upon Thames",
    24:"Richmond upon Thames",
    25:"Hounslow",
    26:"Hillingdon",
    27:"Ealing",
    28:"Brent",
    29:"Harrow",
    30:"Barnet",
    31:"Haringey",
    32:"Enfield",
    33:"Hertsmere",
    38:"Epsom and Ewell",
    40:"Spelthorne",
    57:"London Airport (Heathrow)",
    60:"Allerdale",
    61:"Barrow-in-Furness",
    62:"Carlisle",
    63:"Copeland",
    64:"Eden",
    65:"South Lakeland",
    70:"Blackburn with Darwen",
    71:"Blackpool",
    72:"Burnley",
    73:"Chorley",
    74:"Fylde",
    75:"Hyndburn",
    76:"Lancaster",
    77:"Pendle",
    79:"Preston",
    80:"Ribble Valley",
    82:"Rossendale",
    83:"South Ribble",
    84:"West Lancashire",
    85:"Wyre",
    90:"Knowsley",
    91:"Liverpool",
    92:"St. Helens",
    93:"Sefton",
    95:"Wirral",
    100:"Bolton",
    101:"Bury",
    102:"Manchester",
    104:"Oldham",
    106:"Rochdale",
    107:"Salford",
    109:"Stockport",
    110:"Tameside",
    112:"Trafford",
    114:"Wigan",
    120:"Chester",
    121:"Congleton",
    122:"Crewe and Nantwich",
    123:"Ellesmere Port and Neston",
    124:"Halton",
    126:"Macclesfield",
    127:"Vale Royal",
    128:"Warrington",
    129:"Cheshire East",
    130:"Cheshire West and Chester",
    139:"Northumberland",
    140:"Alnwick",
    141:"Berwick-upon-Tweed",
    142:"Blyth Valley",
    143:"Castle Morpeth",
    144:"Tynedale",
    145:"Wansbeck",
    146:"Gateshead",
    147:"Newcastle upon Tyne",
    148:"North Tyneside",
    149:"South Tyneside",
    150:"Sunderland",
    160:"Chester-le-Street",
    161:"Darlington",
    162:"Derwentside",
    163:"Durham",
    164:"Easington",
    165:"Sedgefield",
    166:"Teesdale",
    168:"Wear Valley",
    169:"County Durham",
    180:"Craven",
    181:"Hambleton",
    182:"Harrogate",
    184:"Richmondshire",
    185:"Ryedale",
    186:"Scarborough",
    187:"Selby",
    189:"York",
    200:"Bradford",
    202:"Calderdale",
    203:"Kirklees",
    204:"Leeds",
    206:"Wakefield",
    210:"Barnsley",
    211:"Doncaster",
    213:"Rotherham",
    215:"Sheffield",
    228:"Kingston upon Hull, City of",
    231:"East Riding of Yorkshire",
    232:"North Lincolnshire",
    233:"North East Lincolnshire",
    240:"Hartlepool",
    241:"Redcar and Cleveland",
    243:"Middlesbrough",
    245:"Stockton-on-Tees",
    250:"Cannock Chase",
    251:"East Staffordshire",
    252:"Lichfield",
    253:"Newcastle-under-Lyme",
    254:"South Staffordshire",
    255:"Stafford",
    256:"Staffordshire Moorlands",
    257:"Stoke-on-Trent",
    258:"Tamworth",
    270:"Bromsgrove",
    273:"Malvern Hills",
    274:"Redditch",
    276:"Worcester",
    277:"Wychavon",
    278:"Wyre Forest",
    279:"Bridgnorth",
    280:"North Shropshire",
    281:"Oswestry",
    282:"Shrewsbury and Atcham",
    283:"South Shropshire",
    284:"Telford and Wrekin",
    285:"Herefordshire, County of ",
    286:"Shropshire",
    290:"North Warwickshire",
    291:"Nuneaton and Bedworth",
    292:"Rugby ",
    293:"Stratford-upon-Avon",
    294:"Warwick",
    300:"Birmingham",
    302:"Coventry",
    303:"Dudley",
    305:"Sandwell",
    306:"Solihull",
    307:"Walsall",
    309:"Wolverhampton",
    320:"Amber Valley",
    321:"Bolsover",
    322:"Chesterfield",
    323:"Derby",
    324:"Erewash",
    325:"High Peak",
    327:"North East Derbyshire",
    328:"South Derbyshire",
    329:"Derbyshire Dales",
    340:"Ashfield",
    341:"Bassetlaw",
    342:"Broxtowe",
    343:"Gedling",
    344:"Mansfield",
    345:"Newark and Sherwood",
    346:"Nottingham",
    347:"Rushcliffe",
    350:"Boston",
    351:"East Lindsey",
    352:"Lincoln",
    353:"North Kesteven",
    354:"South Holland",
    355:"South Kesteven",
    356:"West Lindsey",
    360:"Blaby",
    361:"Hinckley and Bosworth",
    362:"Charnwood",
    363:"Harborough",
    364:"Leicester",
    365:"Melton",
    366:"North West Leicestershire",
    367:"Oadby and Wigston",
    368:"Rutland",
    380:"Corby",
    381:"Daventry",
    382:"East Northamptonshire",
    383:"Kettering",
    384:"Northampton",
    385:"South Northamptonshire",
    386:"Wellingborough",
    390:"Cambridge",
    391:"East Cambridgeshire",
    392:"Fenland",
    393:"Huntingdonshire",
    394:"Peterborough",
    395:"South Cambridgeshire",
    400:"Breckland",
    401:"Broadland",
    402:"Great Yarmouth",
    404:"Norwich",
    405:"North Norfolk",
    406:"South Norfolk",
    407:"King's Lynn and West Norfolk",
    410:"Babergh",
    411:"Forest Heath",
    412:"Ipswich",
    413:"Mid Suffolk",
    414:"St. Edmundsbury",
    415:"Suffolk Coastal",
    416:"Waveney",
    420:"Bedford",
    421:"Luton",
    422:"Mid Bedfordshire",
    423:"South Bedfordshire",
    424:"Central Bedfordshire",
    430:"Broxbourne",
    431:"Dacorum",
    432:"East Hertfordshire",
    433:"North Hertfordshire",
    434:"St. Albans",
    435:"Stevenage",
    436:"Three Rivers",
    437:"Watford",
    438:"Welwyn Hatfield",
    450:"Basildon",
    451:"Braintree",
    452:"Brentwood",
    453:"Castle Point",
    454:"Chelmsford",
    455:"Colchester",
    456:"Epping Forest",
    457:"Harlow",
    458:"Maldon",
    459:"Rochford",
    460:"Southend-on-Sea",
    461:"Tendring",
    462:"Thurrock",
    463:"Uttlesford",
    470:"Bracknell Forest",
    471:"West Berkshire",
    472:"Reading",
    473:"Slough",
    474:"Windsor and Maidenhead",
    475:"Wokingham",
    476:"Aylesbury Vale",
    477:"South Bucks",
    478:"Chiltern",
    479:"Milton Keynes",
    480:"Wycombe",
    481:"Cherwell",
    482:"Oxford",
    483:"Vale of White Horse",
    484:"South Oxfordshire",
    485:"West Oxfordshire",
    490:"Basingstoke and Deane",
    491:"Eastleigh",
    492:"Fareham",
    493:"Gosport",
    494:"Hart",
    495:"Havant",
    496:"New Forest",
    497:"East Hampshire",
    498:"Portsmouth",
    499:"Rushmoor",
    500:"Southampton ",
    501:"Test Valley",
    502:"Winchester",
    505:"Isle of Wight",
    510:"Elmbridge",
    511:"Guildford",
    512:"Mole Valley",
    513:"Reigate and Banstead",
    514:"Runnymede",
    515:"Surrey Heath",
    516:"Tandridge",
    517:"Waverley",
    518:"Woking",
    530:"Ashford",
    531:"Canterbury",
    532:"Dartford",
    533:"Dover",
    535:"Gravesham",
    536:"Maidstone",
    538:"Sevenoaks",
    539:"Shepway",
    540:"Swale",
    541:"Thanet",
    542:"Tonbridge and Malling",
    543:"Tunbridge Wells",
    544:"Medway",
    551:"Eastbourne",
    552:"Hastings",
    554:"Lewes",
    555:"Rother",
    556:"Wealden",
    557:"Adur",
    558:"Arun",
    559:"Chichester",
    560:"Crawley",
    562:"Horsham",
    563:"Mid Sussex",
    564:"Worthing",
    565:"Brighton and Hove",
    570:"City of London",
    580:"East Devon",
    581:"Exeter",
    582:"North Devon",
    583:"Plymouth",
    584:"South Hams",
    585:"Teignbridge",
    586:"Mid Devon",
    587:"Torbay",
    588:"Torridge",
    589:"West Devon",
    590:"Caradon",
    591:"Carrick",
    592:"Kerrier",
    593:"North Cornwall",
    594:"Penwith",
    595:"Restormel",
    596:"Cornwall",
    601:"Bristol, City of",
    605:"North Somerset",
    606:"Mendip",
    607:"Sedgemoor",
    608:"Taunton Deane",
    609:"West Somerset",
    610:"South Somerset",
    611:"Bath and North East Somerset",
    612:"South Gloucestershire",
    620:"Cheltenham",
    621:"Cotswold",
    622:"Forest of Dean",
    623:"Gloucester",
    624:"Stroud",
    625:"Tewkesbury",
    630:"Kennet",
    631:"North Wiltshire",
    632:"Salisbury",
    633:"Swindon",
    634:"West Wiltshire",
    635:"Wiltshire",
    640:"Bournemouth",
    641:"Christchurch",
    642:"North Dorset",
    643:"Poole",
    644:"Purbeck",
    645:"West Dorset",
    646:"Weymouth and Portland",
    647:"East Dorset",
    720:"Isle of Anglesey",
    721:"Conwy",
    722:"Gwynedd",
    723:"Denbighshire",
    724:"Flintshire",
    725:"Wrexham",
    730:"Blaenau Gwent",
    731:"Caerphilly",
    732:"Monmouthshire",
    733:"Newport",
    734:"Torfaen",
    740:"Bridgend",
    741:"Cardiff",
    742:"Merthyr Tydfil",
    743:"Neath Port Talbot",
    744:"Rhondda, Cynon, Taff",
    745:"Swansea",
    746:"The Vale of Glamorgan",
    750:"Ceredigion",
    751:"Carmarthenshire",
    752:"Pembrokeshire",
    753:"Powys",
    910:"Aberdeen City",
    911:"Aberdeenshire",
    912:"Angus",
    913:"Argyll and Bute",
    914:"Scottish Borders",
    915:"Clackmannanshire",
    916:"West Dunbartonshire",
    917:"Dumfries and Galloway",
    918:"Dundee City",
    919:"East Ayrshire",
    920:"East Dunbartonshire",
    921:"East Lothian",
    922:"East Renfrewshire",
    923:"Edinburgh, City of",
    924:"Falkirk",
    925:"Fife",
    926:"Glasgow City",
    927:"Highland",
    928:"Inverclyde",
    929:"Midlothian",
    930:"Moray",
    931:"North Ayrshire",
    932:"North Lanarkshire",
    933:"Orkney Islands",
    934:"Perth and Kinross",
    935:"Renfrewshire",
    936:"Shetland Islands",
    937:"South Ayrshire",
    938:"South Lanarkshire",
    939:"Stirling",
    940:"West Lothian",
    941:"Western Isles",
}